twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@TalesFromADevFlowbite/form/default.html.twig'
        - 'form/fields/custom-checkbox.html.twig'

when@test:
    twig:
        strict_variables: true
